spring:
  h2:
    console:
      enabled: ${H2_CONSOLE_ENABLED}
      setting.web-allow-others: ${H2_WEB_ALLOW_OTHERS}
  datasource:
    url: ${H2_URL}
    username: ${H2_USERNAME}
    password: ${H2_PASSWORD}

registered-client:
  id: ${REGISTERED_CLIENT_ID}
  client-id: ${REGISTERED_CLIENT_CLIENT_ID}
  client-secret: ${REGISTERED_CLIENT_CLIENT_SECRET}
  client-name: ${REGISTERED_CLIENT_CLIENT_NAME}
  redirect-uris: ${REGISTERED_CLIENT_REDIRECT_URI}
  scopes: ${REGISTERED_CLIENT_SCOPES}

dev-user:
  username: ${DEV_USER_USERNAME}
  password: ${DEV_USER_PASSWORD}
  authority: ${DEV_USER_AUTHORITY}